  # Python Build and Test Specifications

  language: python
  
  python:
    - "3.6"
  
  script:
    - python test_api.py
  
  install:
   - pip install -r requirements.txt


# Docker

sudo: required

services:
  - docker