  # Python Build and Test Specifications

  language: python
  
  python:
    - "3.6"
  
  script:
    - python app/test_api.py
  
  install:
   - pip install -r app/requirements.txt


# Docker
sudo: required

services:
  - docker

after_success:

##
## Todo - create the build.json
##

  - docker --version  # document the version travis is using
