# Python Build and Test Specifications

language: python
  
python:
  - "3.6"
  
script:
    - python app/test_api.py
  
install:
   - pip install -r app/requirements.txt


# Docker
sudo: required

services:
    - docker

after_success:
    - ./build/generate_build_info.sh
    - docker --version  # document the version travis is using
